// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Ft1PSM_veD9bp3CfZO3valsCtrqVwcY',
    appId: '1:550658603767:web:721eb2c2fc5992030071f2',
    messagingSenderId: '550658603767',
    projectId: 'khaata-bb7e1',
    authDomain: 'khaata-bb7e1.firebaseapp.com',
    storageBucket: 'khaata-bb7e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFSfgld_uIDX7d8LqokrdwEuNvgwa26rQ',
    appId: '1:550658603767:android:8d3866c70fe9d2450071f2',
    messagingSenderId: '550658603767',
    projectId: 'khaata-bb7e1',
    storageBucket: 'khaata-bb7e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkkdjoivNtirVX0l_RYT3Y6cpIWNHhB7A',
    appId: '1:550658603767:ios:ee34366c6f5c13000071f2',
    messagingSenderId: '550658603767',
    projectId: 'khaata-bb7e1',
    storageBucket: 'khaata-bb7e1.appspot.com',
    iosClientId: '550658603767-nee7trnnfqtr25q32j7lt8gagag3ag5p.apps.googleusercontent.com',
    iosBundleId: 'com.faizan.capital.myCapital',
  );
}
